/**
 * Langage de la création libre, partagé par l'IA du Studio Motion et celle du Montage IA.
 */
/** Le langage de la scène libre : l'IA y dessine n'importe quel visuel. */
export const FREE_DOC = `SCÈNE LIBRE "free" — TU ES LE MOTION DESIGNER : tu dessines et animes CE QUE TU VEUX, comme dans After Effects.
Repère : "x" et "y" = position du CENTRE du calque en fraction de l'écran (0,5 ; 0,5 = centre ; marche en 9:16, 16:9 et 1:1). Toutes les tailles sont en px sur un écran dont le petit côté fait 1080 (largeur en 9:16, hauteur en 16:9).
Valeur animée ("anim") = un nombre / une couleur fixe OU des images clés [{ "t": seconde dans la scène, "v": valeur, "e": "linear" | "in" | "out" | "inOut" | "back" | "elastic" | "bounce" | "expo" }] (la courbe "e" s'applique pour ARRIVER à cette clé ; "expo" et "back" = mouvements pros).
Propriétés communes animables : x, y, scale, sx, sy, rotate (degrés), ry / rx (bascule 3D verticale / horizontale −80…80), opacity (0-1), blur (px). Options : "glow": { "color", "size" px }, "shadow": true, "blend": "add" | "screen" | "multiply" | "overlay", "motionBlur": true (traînée quand ça bouge vite), "from"/"to" (secondes de visibilité).
Calques ("kind") :
- "text" : "text" (max 120, *mot* = couleur d'accent), "size" px (gros titre 120-220, titre 80-110, texte 40-55), "weight" 100-900, "color" anim ou "fill" dégradé, "align", "maxWidth" (fraction de largeur), "tracking" (-0.1…0.6), "upper", "italic", "serif", "stroke": { "color", "width" } (texte détouré), "reveal": "none" | "type" | "rise" | "blur" | "curve" | "split" | "mask" | "scale" | "wave", "revealBy": "char" | "word" | "line", "revealAt", "revealDur".
- "rect" : "w", "h", "radius" (tous animables : une forme peut se transformer en une autre — carte → carré → bouton), "fill" (couleur ou dégradé) ou "color" (anim), "stroke": { "color", "width" }, "progress" (anim 0→1 : le contour se dessine).
- "ellipse" : "w", "h", mêmes options (cercle si h absent).
- "path" : "d" = tracé SVG dans un carré 0-1000 × 0-1000 (centre 500,500), "w" = largeur affichée en px, "color" + "width" (trait), "fill", "progress" (anim 0→1 : le trait se dessine), "start" (anim 0→1 : la queue du trait suit la tête → ligne-comète qui traverse l'écran et guide l'œil vers la scène suivante), "cap". Pour dessiner : logos simplifiés, pictos (éclair, cœur, maison, étoile, flèche, goutte, feuille, ballon…), courbes, soulignés, cadres, graphiques.
- "image" : "src": "logo", "photo:N" (photos du client) ou "search:mots-clés en anglais" (photo libre de droits trouvée sur le web, ex. "search:fresh croissant bakery", "search:basketball court night", "search:abstract blue texture") ; "w", "h", "fit": "cover" | "contain", "radius". Les images "search:" servent pour les objets, lieux, ambiances et textures ; jamais pour représenter une vraie personne identifiable (utilise alors les photos fournies par le client).
- "particles" : "mode": "float" | "burst" | "rain" | "orbit" | "sparkle" | "converge", "count" ≤160, "color", "color2", "size", "spread" (fraction), "speed", "at" (départ).
- "glow" : halo lumineux, "color" (anim), "size" (rayon anim).
- "flow" : rubans de lumière liquide plein écran, "colors": [1 à 4 couleurs], "intensity".
- "group" : "children": [calques] qui bougent ensemble (les enfants gardent leurs x / y d'écran ; déplacer le groupe les déplace tous).
EXEMPLE (signature néon qui se dessine) : { "type": "free", "duration": 3, "bg": { "from": "#0a0620", "to": "#000000", "radial": true }, "camera": { "zoom": [{ "t": 0, "v": 1.3 }, { "t": 1.4, "v": 1, "e": "expo" }] }, "layers": [ { "kind": "glow", "x": 0.5, "y": 0.42, "color": "#7c5cff", "size": [{ "t": 0, "v": 0 }, { "t": 0.9, "v": 650, "e": "out" }], "blend": "add" }, { "kind": "path", "x": 0.5, "y": 0.42, "w": 420, "d": "M 560 60 L 260 560 L 500 560 L 420 940 L 760 380 L 520 380 Z", "color": "#ffffff", "width": 14, "progress": [{ "t": 0.1, "v": 0 }, { "t": 1.1, "v": 1 }], "glow": { "color": "#22d3ee", "size": 40 } }, { "kind": "particles", "x": 0.5, "y": 0.42, "mode": "burst", "count": 70, "color": "#22d3ee", "spread": 0.6, "at": 1.1 }, { "kind": "text", "x": 0.5, "y": 0.68, "text": "VOLT", "size": 190, "weight": 900, "tracking": 0.25, "reveal": "blur", "revealAt": 1.2 } ], "cues": [{ "at": 1.1, "sfx": "impact" }] }
DIRECTION : tu n'es limité par AUCUN modèle. Invente l'esthétique qui sert la marque et la demande du client : néon, luxe minimal, brutalisme / Swiss (aplats, typo géante, blocs qui claquent), Y2K / chrome, papier découpé, éditorial magazine, glassmorphism, rétro 80's, organique (formes douces, couleurs naturelles), data / infographie (barres, courbes et compteurs qui se dessinent), kinetic typography pure, 3D cartes empilées, collage photo… Si le client décrit ou montre un style, REPRODUIS-LE fidèlement avec les calques. Composition pro : hiérarchie claire, 1 idée par scène, marges (rien d'important à moins de 0,08 des bords, zones sûres 9:16), contrastes forts, 2 à 3 couleurs, mouvements avec anticipation et amorti (expo, back), décalages (stagger) entre éléments, caméra qui vit (léger zoom continu), et un bruitage sur chaque impact.`;

