/**
 * Langage de la création libre, partagé par l'IA du Studio Motion et celle du Montage IA.
 */
/** Le langage de la scène libre : l'IA y dessine n'importe quel visuel. */
export const BACKDROP_DOC = `FONDS ANIMÉS HAUT DE GAMME (calculés par la carte graphique) — objet "backdrop" : { "kind": "silk" (soie lumineuse, luxe / tech premium) | "aurora" (aurore boréale, magie, nuit) | "mesh" (dégradé mesh façon Stripe, SaaS, moderne) | "liquid" (métal liquide, chrome, mode, beauté) | "nebula" (espace, étoiles, gaming, futur) | "plasma" (couleurs vives qui ondulent, fête, jeunesse) | "grid" (grille rétro 80's + soleil, synthwave, musique) | "bokeh" (lumières floues, soirée, restaurant, événement) | "lines" (lignes fluides, data, finance, architecture) | "waves" (vagues douces superposées, bien-être, nature, mer) | "grain" (dégradé granuleux éditorial, mode, art) | "paper" (papier clair, artisanal, bio, éditorial — texte sombre) | "marble" (marbre veiné, luxe, immobilier, bijoux) | "fire" (flammes, grill, pizza, sport, énergie) | "ocean" (reflets d'eau, piscine, voyage, fraîcheur) | "sky" (ciel et nuages, rêve, liberté, voyage) | "smoke" (fumée, mystère, parfum, bar) | "holo" (holographique irisé, tech, cosmétique, Y2K) | "tunnel" (tunnel néon, vitesse, gaming, DJ) | "warp" (hyper-espace, lancement, futur) | "hex" (alvéoles, tech, data, miel) | "halftone" (trame pop art, BD, fun) | "topo" (courbes de niveau, outdoor, architecture) | "matrix" (pluie numérique, cyber, IA) | "lava" (lampe à lave, rétro, chill) | "rays" (rayons de lumière, révélation, spirituel) | "ink" (encre dans l'eau, art, beauté) | "sunset" (coucher de soleil sur la mer, été, détente) | "dots" (points ondulants, moderne, musique) | "stripes" (rayures cinétiques, mode, énergie) | "custom", "colors": [1 à 4 "#RRGGBB" du plus sombre au plus lumineux], "speed": 0-4 (1 = normal), "intensity": 0-2.5, "scale": 0.2-5, "angle": degrés, "glsl": seulement pour "custom" }.
- Fond de toute la pub : "theme.backdrop". Fond d'une scène libre : "bg": { "kind": … }. Varie les fonds entre les scènes si la pub change d'ambiance.
- "custom" = TU INVENTES LE FOND demandé par le client (feu, fumée, océan, marbre, néon, motif de marque…) : "glsl" = corps GLSL ES 1.0 d'une fonction vec3 bg(vec2 uv, vec2 p, float t) qui renvoie une couleur 0-1. uv = 0-1, p = coordonnées centrées (-0,5…0,5 en hauteur), t = temps (s). Disponibles : hash(vec2), noise(vec2), fbm(vec2), rot(float) (mat2), pal(float) = palette des 4 couleurs, uC0…uC3 (vec3), uIntensity, uRes. Boucles "for" à bornes constantes ≤ 24 uniquement, pas de "while", pas de texture. Exemple : "float f = fbm(p * 3.0 + vec2(0.0, -t * 0.4)); float flame = smoothstep(0.65, 0.2, p.y + 0.5 - f * 0.6); return pal(f) * flame * 1.4;"`;

export const FREE_DOC = `SCÈNE LIBRE "free" — TU ES LE MOTION DESIGNER : tu dessines et animes CE QUE TU VEUX, comme dans After Effects.
Repère : "x" et "y" = position du CENTRE du calque en fraction de l'écran (0,5 ; 0,5 = centre ; marche en 9:16, 16:9 et 1:1). Toutes les tailles sont en px sur un écran dont le petit côté fait 1080 (largeur en 9:16, hauteur en 16:9).
Valeur animée ("anim") = un nombre / une couleur fixe OU des images clés [{ "t": seconde dans la scène, "v": valeur, "e": "linear" | "in" | "out" | "inOut" | "back" | "elastic" | "bounce" | "expo" }] (la courbe "e" s'applique pour ARRIVER à cette clé ; "expo" et "back" = mouvements pros).
Propriétés communes animables : x, y, scale, sx, sy, rotate (degrés), ry / rx (bascule 3D verticale / horizontale −80…80), opacity (0-1), blur (px). Options : "glow": { "color", "size" px }, "shadow": true, "blend": "add" | "screen" | "multiply" | "overlay", "motionBlur": true (traînée quand ça bouge vite), "from"/"to" (secondes de visibilité).
Calques ("kind") :
- "text" : "text" (max 120, *mot* = couleur d'accent), "size" px (gros titre 120-220, titre 80-110, texte 40-55), "weight" 100-900, "color" anim ou "fill" dégradé, "align", "maxWidth" (fraction de largeur), "tracking" (-0.1…0.6), "upper", "italic", "serif", "stroke": { "color", "width" } (texte détouré), "reveal": "none" | "type" | "rise" | "blur" | "curve" | "split" | "mask" | "scale" | "wave", "revealBy": "char" | "word" | "line", "revealAt", "revealDur".
- "rect" : "w", "h", "radius" (tous animables : une forme peut se transformer en une autre — carte → carré → bouton), "fill" (couleur ou dégradé) ou "color" (anim), "stroke": { "color", "width" }, "progress" (anim 0→1 : le contour se dessine).
- "ellipse" : "w", "h", mêmes options (cercle si h absent).
- "path" : "d" = tracé SVG dans un carré 0-1000 × 0-1000 (centre 500,500), "w" = largeur affichée en px, "color" + "width" (trait), "fill", "progress" (anim 0→1 : le trait se dessine), "start" (anim 0→1 : la queue du trait suit la tête → ligne-comète qui traverse l'écran et guide l'œil vers la scène suivante), "cap". Pour dessiner : logos simplifiés, pictos (éclair, cœur, maison, étoile, flèche, goutte, feuille, ballon…), courbes, soulignés, cadres, graphiques.
- "image" : "src": "logo", "photo:N" (photos du client) ou "search:mots-clés en anglais" (photo libre de droits trouvée sur le web, ex. "search:fresh croissant bakery") ; "w", "h", "fit": "cover" | "contain", "radius", "stroke", "zoom" (anim, 1 = cadrage complet, 2-3 = gros plan) + "fx" / "fy" (anim 0-1 = point DE L'IMAGE visé par le zoom), "reveal": "none" | "wipe" | "iris" | "blinds" | "split" | "rise" + "revealAt" / "revealDur". Les images "search:" servent pour les objets, lieux, ambiances et textures ; jamais pour représenter une vraie personne identifiable.
- "callout" : annotation qui EXPLIQUE un détail : "x" / "y" = point visé à l'écran (fraction), "tx" / "ty" = position de l'étiquette, "text" (max 60), "sub" (précision, max 60), "color", "size" (px, 30-50), "at" (seconde d'apparition). Le point pulse, un trait se dessine jusqu'à l'étiquette, l'étiquette apparaît.
- "particles" : "mode": "float" | "burst" | "rain" | "orbit" | "sparkle" | "converge", "count" ≤160, "color", "color2", "size", "spread" (fraction), "speed", "at" (départ).
- "glow" : halo lumineux, "color" (anim), "size" (rayon anim).
- "flow" : rubans de lumière liquide plein écran, "colors": [1 à 4 couleurs], "intensity".
- "group" : "children": [calques] qui bougent ensemble (les enfants gardent leurs x / y d'écran ; déplacer le groupe les déplace tous).
EXEMPLE (signature néon qui se dessine) : { "type": "free", "duration": 3, "bg": { "from": "#0a0620", "to": "#000000", "radial": true }, "camera": { "zoom": [{ "t": 0, "v": 1.3 }, { "t": 1.4, "v": 1, "e": "expo" }] }, "layers": [ { "kind": "glow", "x": 0.5, "y": 0.42, "color": "#7c5cff", "size": [{ "t": 0, "v": 0 }, { "t": 0.9, "v": 650, "e": "out" }], "blend": "add" }, { "kind": "path", "x": 0.5, "y": 0.42, "w": 420, "d": "M 560 60 L 260 560 L 500 560 L 420 940 L 760 380 L 520 380 Z", "color": "#ffffff", "width": 14, "progress": [{ "t": 0.1, "v": 0 }, { "t": 1.1, "v": 1 }], "glow": { "color": "#22d3ee", "size": 40 } }, { "kind": "particles", "x": 0.5, "y": 0.42, "mode": "burst", "count": 70, "color": "#22d3ee", "spread": 0.6, "at": 1.1 }, { "kind": "text", "x": 0.5, "y": 0.68, "text": "VOLT", "size": 190, "weight": 900, "tracking": 0.25, "reveal": "blur", "revealAt": 1.2 } ], "cues": [{ "at": 1.1, "sfx": "impact" }] }
DIRECTION : tu n'es limité par AUCUN modèle. Invente l'esthétique qui sert la marque et la demande du client : néon, luxe minimal, brutalisme / Swiss (aplats, typo géante, blocs qui claquent), Y2K / chrome, papier découpé, éditorial magazine, glassmorphism, rétro 80's, organique (formes douces, couleurs naturelles), data / infographie (barres, courbes et compteurs qui se dessinent), kinetic typography pure, 3D cartes empilées, collage photo… Si le client décrit ou montre un style, REPRODUIS-LE fidèlement avec les calques. Composition pro : hiérarchie claire, 1 idée par scène, marges (rien d'important à moins de 0,08 des bords, zones sûres 9:16), contrastes forts, 2 à 3 couleurs, mouvements avec anticipation et amorti (expo, back), décalages (stagger) entre éléments, caméra qui vit (léger zoom continu), et un bruitage sur chaque impact.

IMAGES DU CLIENT = INFORMATIONS À FAIRE COMPRENDRE (règle forte) : chaque photo fournie devient une scène "free" qui l'ANIME pour l'expliquer, pas un simple diaporama.
- Utilise les « points clés » des notes de photos (coordonnées dans la photo) : zoom progressif ("zoom" + "fx"/"fy") vers le détail important, puis "callout" qui le nomme (matière, prix réel, ingrédient, fonction, lieu, résultat…). Pour placer un callout sur l'image affichée en plein écran (w = largeur d'écran, "fit": "cover") : x ≈ fx, y ≈ fy de l'image.
- Enchaîne les idées : vue d'ensemble → gros plan → annotation ; avant / après (deux images côte à côte ou volet "wipe") ; image qui se dévoile ("iris", "blinds") sur le mot clé ; image dans un cadre qui pivote (ry) avec un chiffre réel qui compte à côté ; plusieurs images en grille qui apparaissent en décalé.
- Le texte explique ce que l'image prouve (« Fait à la main », « Livré en 24 h », vrais faits du client) et ne cache jamais le sujet.

${BACKDROP_DOC}`;
